### ISSUE TITLE
Instruction email has typos and css

### ISSUE THREAD

**Issue by thijskh** [encryption4all/postguard-tb-addon#13]
I received a PostGuard encrypted mail with this text in it:

```
2
You can also decrypt and read this email via the fallback website [www.postguard.eu/decrypt/](http://www.postguard.eu/decrypt/) [<https://www.postguard.eu/decrypt/>](https://www.postguard.eu/decrypt/). This website only decrypts the mail, and cannot be used for replying. PostGuards work better with its add-on than with this website.
.d{fill:#fff;}.e{fill:#54d6a7;}.f{fill:#022e3d;}.g{fill:#181817;}
```

The stray CSS in the plain text and the misspelling of "PostGuards work better" give it a bit of a "phishy" impression.

**Comment by leonbotros** [comment]
Thanks, we'll take a look. We plan to shorten the HTML/plaintext and refer to an actual instruction page on our website.
This way, we do not have the issue with outdated instructions floating around in everyone's inbox.
